<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sheneli Weerasinghe">

<title>Forecasting US Retail Sales Using Time Series Models in R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Project 1 Retail Forecasting_files/libs/clipboard/clipboard.min.js"></script>
<script src="Project 1 Retail Forecasting_files/libs/quarto-html/quarto.js"></script>
<script src="Project 1 Retail Forecasting_files/libs/quarto-html/popper.min.js"></script>
<script src="Project 1 Retail Forecasting_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Project 1 Retail Forecasting_files/libs/quarto-html/anchor.min.js"></script>
<link href="Project 1 Retail Forecasting_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Project 1 Retail Forecasting_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Project 1 Retail Forecasting_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Project 1 Retail Forecasting_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Project 1 Retail Forecasting_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Forecasting US Retail Sales Using Time Series Models in R</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sheneli Weerasinghe </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="executive-summary" class="level1">
<h1>Executive Summary</h1>
<p>Retail businesses rely on accurate demand forecasts to plan inventory, staffing, and promotional activity. This project develops time-series forecasting models to predict monthly US clothing retail sales using data from the Federal Reserve Economic Data (FRED) database.</p>
<p>A logarithmic transformation was applied to stabilize variance, and seasonal differencing was used to address strong annual patterns in retail demand. Several ARIMA and ETS models were estimated and evaluated using out-of-sample forecast accuracy and residual diagnostics.</p>
<p>The ARIMA model provided the most reliable forecasts, outperforming ETS based on both accuracy metrics and Ljung–Box tests. The results highlight strong and predictable seasonal peaks in retail sales, particularly during the holiday period, which can support planning decisions related to inventory management, staffing, and promotional timing.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fredr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'fredr' was built under R version 4.4.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyverse' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyr' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'readr' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'purrr' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'dplyr' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'stringr' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'forcats' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'lubridate' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tsibble)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tsibble' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'tsibble'

The following object is masked from 'package:lubridate':

    interval

The following objects are masked from 'package:base':

    intersect, setdiff, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fable)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'fable' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: fabletools</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'fabletools' was built under R version 4.4.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fpp3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'fpp3' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 methods overwritten by 'ggtime':
  method                  from      
  +.gg_tsensemble         feasts    
  autolayer.fbl_ts        fabletools
  autolayer.tbl_ts        fabletools
  autoplot.dcmp_ts        fabletools
  autoplot.fbl_ts         fabletools
  autoplot.tbl_cf         feasts    
  autoplot.tbl_ts         fabletools
  fortify.fbl_ts          fabletools
  grid.draw.gg_tsensemble feasts    
  print.gg_tsensemble     feasts    
  scale_type.cf_lag       feasts    </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: replacing previous import 'feasts::scale_x_cf_lag' by
'ggtime::scale_x_cf_lag' when loading 'fpp3'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: replacing previous import 'feasts::gg_season' by 'ggtime::gg_season'
when loading 'fpp3'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: replacing previous import 'feasts::gg_tsresiduals' by
'ggtime::gg_tsresiduals' when loading 'fpp3'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: replacing previous import 'feasts::gg_irf' by 'ggtime::gg_irf' when
loading 'fpp3'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: replacing previous import 'feasts::gg_arma' by 'ggtime::gg_arma' when
loading 'fpp3'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: replacing previous import 'feasts::gg_tsdisplay' by
'ggtime::gg_tsdisplay' when loading 'fpp3'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: replacing previous import 'feasts::gg_subseries' by
'ggtime::gg_subseries' when loading 'fpp3'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: replacing previous import 'feasts::gg_lag' by 'ggtime::gg_lag' when
loading 'fpp3'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ──────────────────────────────────────────── fpp3 1.0.3 ──
✔ tsibbledata 0.4.1     ✔ feasts      0.4.1
✔ ggtime      0.2.0     </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tsibbledata' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggtime' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'feasts' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ───────────────────────────────────────────────── fpp3_conflicts ──
✖ lubridate::date()        masks base::date()
✖ dplyr::filter()          masks stats::filter()
✖ feasts::gg_arma()        masks ggtime::gg_arma()
✖ feasts::gg_irf()         masks ggtime::gg_irf()
✖ feasts::gg_lag()         masks ggtime::gg_lag()
✖ feasts::gg_season()      masks ggtime::gg_season()
✖ feasts::gg_subseries()   masks ggtime::gg_subseries()
✖ feasts::gg_tsdisplay()   masks ggtime::gg_tsdisplay()
✖ feasts::gg_tsresiduals() masks ggtime::gg_tsresiduals()
✖ tsibble::intersect()     masks base::intersect()
✖ tsibble::interval()      masks lubridate::interval()
✖ dplyr::lag()             masks stats::lag()
✖ feasts::scale_x_cf_lag() masks ggtime::scale_x_cf_lag()
✖ tsibble::setdiff()       masks base::setdiff()
✖ tsibble::union()         masks base::union()</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'scales'

The following object is masked from 'package:purrr':

    discard

The following object is masked from 'package:readr':

    col_factor</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fredr_set_key</span>(<span class="st">"cb159db4ea49603bda6644759f19936d"</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>retail_sales <span class="ot">&lt;-</span> <span class="fu">fredr</span>(</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">series_id =</span> <span class="st">"RSCCASN"</span>,</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">observation_start =</span> <span class="fu">as.Date</span>(<span class="st">"1992-01-01"</span>)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>retail_ts <span class="ot">&lt;-</span> retail_sales <span class="sc">|&gt;</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(date, value) <span class="sc">|&gt;</span></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Month =</span> date, <span class="at">Sales =</span> value) <span class="sc">|&gt;</span></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">Month =</span> <span class="fu">yearmonth</span>(Month),</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">Sales =</span> Sales <span class="sc">/</span> <span class="dv">1000</span>   <span class="co"># convert millions → billions</span></span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tsibble</span>(<span class="at">index =</span> Month)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="plotting-the-data-describing-the-statistical-features" class="level1">
<h1>Plotting the Data &amp; Describing the Statistical Features</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(retail_ts, Sales) <span class="sc">+</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="at">title =</span> <span class="st">"Monthly US Clothing Retail Sales"</span>,</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="at">y =</span> <span class="st">"Sales ($ Billion)"</span>,</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="at">x =</span> <span class="st">"Month"</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project-1-Retail-Forecasting_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The monthly retail data shows that there has been a general upwards trend since 1992. There are two shocks present were sales decreased temporarily. The first was a small shock around 2008, likely due to the GFC. The second was a very large shock around 2020, likely due to COVID. There also appears to be a strong seasonal pattern present.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gg_season</span>(retail_ts, <span class="at">labels=</span><span class="st">"both"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Sale ($ Billion)"</span>, <span class="at">title =</span> <span class="st">"Seasonal Plot: US Clothing Retail Sales"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Plot variable not specified, automatically selected `y = Sales`</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project-1-Retail-Forecasting_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This graph shows that sales increase every year from November to December, likely due to people spending more on clothing around the Christmas period. There also seems to be in an increase in the level of seasonality throughout the years, which makes a box-cox transformation appropriate.</p>
</section>
<section id="box-cox-transformation" class="level1">
<h1>Box-Cox Transformation</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>retail_ts <span class="sc">|&gt;</span> <span class="fu">features</span>(Sales, <span class="at">features=</span> guerrero) <span class="sc">|&gt;</span> <span class="fu">pull</span>(lambda_guerrero)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4243897</code></pre>
</div>
</div>
<p>The appropriate Box Cox transformation is λ = 0.4243897.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>retail_ts <span class="sc">|&gt;</span> <span class="fu">autoplot</span>(<span class="fu">box_cox</span>(Sales, <span class="fl">0.4243897</span>)) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Box Cox Sales, 0.4243897 ($ Billion)"</span>, <span class="at">title =</span> <span class="st">"Transformed Turnover with λ = 0.4243897"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project-1-Retail-Forecasting_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>ldcomp <span class="ot">&lt;-</span> retail_ts <span class="sc">|&gt;</span> <span class="fu">model</span>(<span class="at">stl =</span> <span class="fu">STL</span>(<span class="fu">box_cox</span>(Sales, <span class="fl">0.4243897</span>)))</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">components</span>(ldcomp) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A dable: 409 x 7 [1M]
# Key:     .model [1]
# :        box_cox(Sales, 0.4243897) = trend + season_year + remainder
   .model    Month `box_cox(Sales, 0.4243897)` trend season_year remainder
   &lt;chr&gt;     &lt;mth&gt;                       &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt;     &lt;dbl&gt;
 1 stl    1992 Jan                        2.94  3.74    -0.839     0.0356 
 2 stl    1992 Feb                        3.12  3.75    -0.664     0.0368 
 3 stl    1992 Mar                        3.41  3.76    -0.237    -0.108  
 4 stl    1992 Apr                        3.67  3.77    -0.133     0.0404 
 5 stl    1992 May                        3.71  3.77    -0.0243   -0.0368 
 6 stl    1992 Jun                        3.61  3.78    -0.160    -0.0116 
 7 stl    1992 Jul                        3.59  3.79    -0.199    -0.00441
 8 stl    1992 Aug                        3.96  3.80     0.154     0.0115 
 9 stl    1992 Sep                        3.72  3.81    -0.116     0.0268 
10 stl    1992 Oct                        3.90  3.81    -0.00400   0.0869 
# ℹ 399 more rows
# ℹ 1 more variable: season_adjust &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">components</span>(ldcomp) <span class="sc">|&gt;</span> <span class="fu">autoplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project-1-Retail-Forecasting_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The STL decomposition highlights a strong and stable seasonal pattern in retail sales. There also appears to be a clear upward trend, even without the effect of seasonality. The remainder component shows a large spike around 2020, reflecting the impact of the COVID-19 shock. This indicates that STL decomposition, cannot explain all the structure in the data, and further analysis must be done.</p>
</section>
<section id="differencing-to-make-data-stationary" class="level1">
<h1>Differencing to Make Data Stationary</h1>
<section id="training-and-test-set" class="level2">
<h2 class="anchored" data-anchor-id="training-and-test-set">Training and Test Set</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>ret_tr <span class="ot">&lt;-</span> retail_ts[<span class="dv">1</span><span class="sc">:</span><span class="dv">385</span>,]</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>ret_ts <span class="ot">&lt;-</span> retail_ts[<span class="dv">386</span><span class="sc">:</span><span class="dv">409</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>A test set was created using the last 24 months of data. The rest of the data was placed into a training set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>ret_tr <span class="sc">|&gt;</span> <span class="fu">features</span>(Sales, unitroot_nsdiffs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  nsdiffs
    &lt;int&gt;
1       1</code></pre>
</div>
</div>
<p>The data contains seasonality, therefore differencing is required to prevent biased forecasts. A unit root test determined that one seasonal difference needed to be added, which a lag of 12.</p>
<p>The Guerrero method suggested a Box-Cox transformation with λ ≈ 0.42. However, a logarithmic transformation (λ = 0) was used instead for simplicity and interpretability, as it effectively stabilizes variance and allows changes to be interpreted as approximate percentage growth.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>ret_tr <span class="sc">|&gt;</span> <span class="fu">gg_tsdisplay</span>(<span class="fu">difference</span>(<span class="fu">log</span>(Sales), <span class="at">lag =</span> <span class="dv">12</span>), <span class="at">plot_type =</span> <span class="st">"partial"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Differenced Retail Data (Jan 1992 - Jan 2026) Residual Plots"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 12 rows containing missing values or values outside the scale range
(`geom_line()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 12 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project-1-Retail-Forecasting_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>There appears to still be a trend in the data and the unit root test is used to confirm this.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>ret_tr <span class="sc">|&gt;</span> <span class="fu">features</span>(<span class="fu">difference</span>(<span class="fu">log</span>(Sales), <span class="at">lag =</span> <span class="dv">12</span>), unitroot_kpss)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  kpss_stat kpss_pvalue
      &lt;dbl&gt;       &lt;dbl&gt;
1    0.0419         0.1</code></pre>
</div>
</div>
<p>The p-value is 0.0419, supporting the hypothesis that the data is still not stationary. However, a unit root ordinary difference test indicated that ordinary differences needed to be added. The series is likely not stationary due to the sales drop that occurred around COVID.</p>
<pre><code>ret_tr |&gt; features(difference(log(Sales), lag = 12), unitroot_ndiffs)</code></pre>
</section>
</section>
<section id="creating-a-shortlist-of-arima-and-ets-models" class="level1">
<h1>Creating a Shortlist of ARIMA and ETS Models</h1>
<section id="ets-models" class="level2">
<h2 class="anchored" data-anchor-id="ets-models">ETS Models</h2>
<section id="choosing-appropriate-ets-models" class="level3">
<h3 class="anchored" data-anchor-id="choosing-appropriate-ets-models">Choosing Appropriate ETS Models</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>ETS_fit <span class="ot">&lt;-</span> ret_tr <span class="sc">|&gt;</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">model</span>(<span class="at">ETS =</span> <span class="fu">ETS</span>(Sales), <span class="at">Drift =</span> <span class="fu">RW</span>(Sales<span class="sc">~</span><span class="fu">drift</span>()), <span class="at">NAIVE =</span> <span class="fu">NAIVE</span>(Sales), <span class="at">SNAIVE =</span> <span class="fu">SNAIVE</span>(Sales))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The ETS model automatically chosen was ETS(M,N,M). The benchmarks random walk, snaive and naive were chosen. Mean was not chosen as a benchmark due to seasonality and an increasing trend in the data. The other benchmarks were more appropriate.</p>
<p>Other potential models were considered. The first is the Damped Holt’s method, which may be more accurate due to dampening the effect of the trend.</p>
<p>Two more potential models that can be tested are the same Holt and Damped Holt models as above, but with additive errors.</p>
<p>So the short list of ETS models are: Holt(M,N,M) Damped Holt(M,Ad,M) Holt(A,N,M) Damped Holt(A,Ad,M)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>ETS_fit <span class="ot">&lt;-</span> ret_tr <span class="sc">|&gt;</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">Holt_MNM     =</span> <span class="fu">ETS</span>(Sales <span class="sc">~</span> <span class="fu">error</span>(<span class="st">"M"</span>) <span class="sc">+</span> <span class="fu">trend</span>(<span class="st">"N"</span>) <span class="sc">+</span> <span class="fu">season</span>(<span class="st">"M"</span>)),</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Damped_MAdM  =</span> <span class="fu">ETS</span>(Sales <span class="sc">~</span> <span class="fu">error</span>(<span class="st">"M"</span>) <span class="sc">+</span> <span class="fu">trend</span>(<span class="st">"Ad"</span>, <span class="at">phi =</span> <span class="fl">0.9</span>) <span class="sc">+</span> <span class="fu">season</span>(<span class="st">"M"</span>)),</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Holt_ANM     =</span> <span class="fu">ETS</span>(Sales <span class="sc">~</span> <span class="fu">error</span>(<span class="st">"A"</span>) <span class="sc">+</span> <span class="fu">trend</span>(<span class="st">"N"</span>) <span class="sc">+</span> <span class="fu">season</span>(<span class="st">"M"</span>)),</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Damped_AAdM  =</span> <span class="fu">ETS</span>(Sales <span class="sc">~</span> <span class="fu">error</span>(<span class="st">"A"</span>) <span class="sc">+</span> <span class="fu">trend</span>(<span class="st">"Ad"</span>, <span class="at">phi =</span> <span class="fl">0.9</span>) <span class="sc">+</span> <span class="fu">season</span>(<span class="st">"M"</span>))</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(ETS_fit) <span class="sc">|&gt;</span> <span class="fu">select</span>(.model, AIC, AICc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  .model        AIC  AICc
  &lt;chr&gt;       &lt;dbl&gt; &lt;dbl&gt;
1 Holt_MNM    2461. 2463.
2 Damped_MAdM 2468. 2470.
3 Holt_ANM    2478. 2479.
4 Damped_AAdM 2471. 2472.</code></pre>
</div>
</div>
<p>The model with the lowest AIC and AICc is the Holt ETS(M,N,M) model, which was the automatic model. The next lowest model is the Damped ETS(M,Ad,M) model which has an AIC and AICc that is higher than the Holt (M,A,M) model by 6-7. The Holt (A,N,M) and Damped (A,Ad,M) models have much slightly higher AICs and AICcs compared to the Holt (M,N,M) and Damped (M,Ad,M)</p>
</section>
<section id="testing-the-accuracy-of-the-ets-models-on-the-test-set" class="level3">
<h3 class="anchored" data-anchor-id="testing-the-accuracy-of-the-ets-models-on-the-test-set">Testing the accuracy of the ETS Models on the Test Set</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>ETS_fc1 <span class="ot">&lt;-</span> <span class="fu">forecast</span>(ETS_fit, <span class="at">h=</span><span class="dv">24</span>) <span class="sc">|&gt;</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(.model<span class="sc">==</span><span class="st">'Holt_MNM'</span>) </span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>ETS_fc2 <span class="ot">&lt;-</span> <span class="fu">forecast</span>(ETS_fit, <span class="at">h=</span><span class="dv">24</span>) <span class="sc">|&gt;</span></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(.model<span class="sc">==</span><span class="st">'Damped_MAdM'</span>) </span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>ETS_fc3 <span class="ot">&lt;-</span> <span class="fu">forecast</span>(ETS_fit, <span class="at">h=</span><span class="dv">24</span>) <span class="sc">|&gt;</span></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(.model<span class="sc">==</span><span class="st">'Holt_ANM'</span>) </span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a>ETS_fc4 <span class="ot">&lt;-</span> <span class="fu">forecast</span>(ETS_fit, <span class="at">h=</span><span class="dv">24</span>) <span class="sc">|&gt;</span></span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(.model<span class="sc">==</span><span class="st">'Damped_AAdM'</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>First produce forecasts for the test data using each model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>ETS_fc_accuracy <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">accuracy</span>(ETS_fc1, ret_ts) <span class="sc">|&gt;</span> <span class="fu">select</span>(.model, RMSE),</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">accuracy</span>(ETS_fc2, ret_ts) <span class="sc">|&gt;</span> <span class="fu">select</span>(.model, RMSE),</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">accuracy</span>(ETS_fc3, ret_ts) <span class="sc">|&gt;</span> <span class="fu">select</span>(.model, RMSE),</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">accuracy</span>(ETS_fc4, ret_ts) <span class="sc">|&gt;</span> <span class="fu">select</span>(.model, RMSE)</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(ETS_fc_accuracy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  .model       RMSE
  &lt;chr&gt;       &lt;dbl&gt;
1 Holt_MNM     1.76
2 Damped_MAdM  1.76
3 Holt_ANM     1.70
4 Damped_AAdM  1.85</code></pre>
</div>
</div>
<p>The model with the lowest RMSE is the Damped (A,Ad,M) model, even though it performed the second worst for AIC. The Damped (M,N,M) and Damped(M,Ad,M) model have an RMSE that is only slightly higher. The Holt (A,N,M) performed the best for RMSE.</p>
<p>Therefore, when taking both AIC and RMSE into account, the best model is Holt ETS (M,N,M) as it performs the best for AIC and the second best for RMSE.</p>
</section>
</section>
<section id="arima-models" class="level2">
<h2 class="anchored" data-anchor-id="arima-models">ARIMA Models</h2>
<p>Several candidate ARIMA models were estimated based on ACF/PACF diagnostics. These models were compared using AICc, out-of-sample forecast accuracy, and residual diagnostics.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>ret_tr <span class="sc">|&gt;</span> <span class="fu">gg_tsdisplay</span>(<span class="fu">difference</span>(<span class="fu">log</span>(Sales), <span class="at">lag =</span> <span class="dv">12</span>), <span class="at">plot_type =</span> <span class="st">"partial"</span>, <span class="at">lag_max =</span> <span class="dv">84</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Differenced Retail Data (Jan 1992 - Jan 2026) Residual Plots"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 12 rows containing missing values or values outside the scale range
(`geom_line()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 12 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project-1-Retail-Forecasting_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="arima-model-based-on-acf" class="level3">
<h3 class="anchored" data-anchor-id="arima-model-based-on-acf">ARIMA Model based on ACF</h3>
<p>The ACF plot shows 7 significant lags before lag 12, therefore q = 7. The last significant seasonal lag is at 12, therefore Q = 1. So one potential model is ARIMA(0,0,7)(0,1,1)[12]</p>
<p>However, lag 6 &amp; 7 are only slightly significant .Therefore q can also = 5 So another potential model is ARIMA(0,0,5)(0,1,1)[12]</p>
</section>
<section id="arima-model-based-on-pacf" class="level3">
<h3 class="anchored" data-anchor-id="arima-model-based-on-pacf">ARIMA Model based on PACF</h3>
<p>There are 6 significant lags before lag 12, therefore p = 6. The last significant seasonal lag is at 72 therefore P = 6. So the model based on PACF is ARIMA(6,0,0)(6,1,0)[12]. Lag 24 is barely significant, therefore P=2. So another potential model is ARIMA(6,0,0)(2,1,0)[12]</p>
<p>So 4 potential models are a1 = ARIMA(0,0,7)(0,1,1)[12], a2 = ARIMA(0,0,5)(0,1,1)[12], a3 = ARIMA(6,0,0)(6,1,0)[12] &amp; a4 = ARIMA(6,0,0)(2,1,0)[12].</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>AR_fit <span class="ot">&lt;-</span> ret_tr <span class="sc">|&gt;</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">model</span>(<span class="at">a1 =</span> <span class="fu">ARIMA</span>(<span class="fu">log</span>(Sales) <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> <span class="fu">pdq</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">7</span>) <span class="sc">+</span> <span class="fu">PDQ</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>)),</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a><span class="at">a2 =</span> <span class="fu">ARIMA</span>(<span class="fu">log</span>(Sales) <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> <span class="fu">pdq</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">5</span>) <span class="sc">+</span> <span class="fu">PDQ</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>)),</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a><span class="at">a3 =</span> <span class="fu">ARIMA</span>(<span class="fu">log</span>(Sales) <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> <span class="fu">pdq</span>(<span class="dv">6</span>,<span class="dv">0</span>,<span class="dv">0</span>) <span class="sc">+</span> <span class="fu">PDQ</span>(<span class="dv">6</span>,<span class="dv">1</span>,<span class="dv">0</span>)),</span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a><span class="at">a4 =</span> <span class="fu">ARIMA</span>(<span class="fu">log</span>(Sales) <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> <span class="fu">pdq</span>(<span class="dv">6</span>,<span class="dv">0</span>,<span class="dv">0</span>) <span class="sc">+</span> <span class="fu">PDQ</span>(<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">0</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="forecast-models" class="level3">
<h3 class="anchored" data-anchor-id="forecast-models">Forecast models</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>AR_fc1 <span class="ot">&lt;-</span> <span class="fu">forecast</span>(AR_fit, <span class="at">h=</span><span class="dv">24</span>) <span class="sc">|&gt;</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(.model<span class="sc">==</span><span class="st">'a1'</span>) </span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>AR_fc2 <span class="ot">&lt;-</span> <span class="fu">forecast</span>(AR_fit, <span class="at">h=</span><span class="dv">24</span>) <span class="sc">|&gt;</span></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(.model<span class="sc">==</span><span class="st">'a2'</span>) </span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>AR_fc3 <span class="ot">&lt;-</span> <span class="fu">forecast</span>(AR_fit, <span class="at">h=</span><span class="dv">24</span>) <span class="sc">|&gt;</span></span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(.model<span class="sc">==</span><span class="st">'a3'</span>) </span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a>AR_fc4 <span class="ot">&lt;-</span> <span class="fu">forecast</span>(AR_fit, <span class="at">h=</span><span class="dv">24</span>) <span class="sc">|&gt;</span></span>
<span id="cb67-11"><a href="#cb67-11" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(.model<span class="sc">==</span><span class="st">'a4'</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="aic-and-rmse-of-the-arima-models" class="level3">
<h3 class="anchored" data-anchor-id="aic-and-rmse-of-the-arima-models">AIC and RMSE of the ARIMA Models</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(AR_fit) <span class="sc">|&gt;</span> <span class="fu">select</span>(.model,AIC, AICc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  .model   AIC  AICc
  &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt;
1 a1     -574. -573.
2 a2     -574. -574.
3 a3     -613. -612.
4 a4     -549. -548.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>AR_fc_accuracy <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">accuracy</span>(AR_fc1, ret_ts) <span class="sc">|&gt;</span> <span class="fu">select</span>(.model, RMSE),</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">accuracy</span>(AR_fc2, ret_ts) <span class="sc">|&gt;</span> <span class="fu">select</span>(.model, RMSE),</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">accuracy</span>(AR_fc3, ret_ts) <span class="sc">|&gt;</span> <span class="fu">select</span>(.model, RMSE),</span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">accuracy</span>(AR_fc4, ret_ts) <span class="sc">|&gt;</span> <span class="fu">select</span>(.model, RMSE)</span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(AR_fc_accuracy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  .model  RMSE
  &lt;chr&gt;  &lt;dbl&gt;
1 a1      3.57
2 a2      3.51
3 a3      5.13
4 a4      1.30</code></pre>
</div>
</div>
<p>a3 has the lowest AIC and AICc by far, however is also has the highest RMSE by far as well. a4 has the lowest RMSE by far and the second lowest AIC/AICc. Therefore based on these metrics, ARIMA(6,0,0)(2,1,0)[12] has been chosen as the preferred model.</p>
</section>
</section>
</section>
<section id="best-arima-and-ets" class="level1">
<h1>Best ARIMA and ETS</h1>
<p>The best models chosen for ETS and ARIMA had forecasts produced based on training data. The accuracy of each forecast was compared in order to determine which model is more likely to produce a better forecast for the future.</p>
<section id="forecasts-based-on-training-data" class="level2">
<h2 class="anchored" data-anchor-id="forecasts-based-on-training-data">Forecasts Based on Training Data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>ETS_fc1 <span class="sc">|&gt;</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(ret_tr) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Sales ($ Billion)"</span>, <span class="at">title =</span> <span class="st">"ETS Jan 2024-Jan 2026 Forecast of US Clothing Sales"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project-1-Retail-Forecasting_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>AR_fc4 <span class="sc">|&gt;</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(ret_tr) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Sales ($ Billion)"</span>, <span class="at">title =</span> <span class="st">"ARIMA Jan 2024-Jan 2026 Forecast of US Clothing Sales"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project-1-Retail-Forecasting_files/figure-html/unnamed-chunk-19-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="reporting-parameters" class="level2">
<h2 class="anchored" data-anchor-id="reporting-parameters">Reporting Parameters</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(AR_fit) <span class="sc">|&gt;</span> <span class="fu">filter</span>(.model<span class="sc">==</span><span class="st">'a4'</span>) <span class="sc">|&gt;</span> <span class="fu">select</span>(term, estimate, std.error, statistic,p.value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 5
  term  estimate std.error statistic  p.value
  &lt;chr&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 ar1     0.907     0.0518    17.5   1.34e-50
2 ar2    -0.450     0.0704    -6.39  4.89e-10
3 ar3     0.300     0.0736     4.08  5.55e- 5
4 ar4    -0.0788    0.0737    -1.07  2.86e- 1
5 ar5     0.0211    0.0696     0.304 7.61e- 1
6 ar6     0.0761    0.0511     1.49  1.37e- 1
7 sar1   -0.602     0.0500   -12.0   2.09e-28
8 sar2   -0.276     0.0488    -5.65  3.14e- 8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(ETS_fit) <span class="sc">|&gt;</span> <span class="fu">filter</span>(.model<span class="sc">==</span><span class="st">'Holt_MNM'</span>) <span class="sc">|&gt;</span> <span class="fu">select</span>(term, estimate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 15 × 2
   term   estimate
   &lt;chr&gt;     &lt;dbl&gt;
 1 alpha     0.229
 2 gamma     0.120
 3 l[0]      9.43 
 4 s[0]      1.76 
 5 s[-1]     1.11 
 6 s[-2]     0.984
 7 s[-3]     0.925
 8 s[-4]     1.03 
 9 s[-5]     0.913
10 s[-6]     0.925
11 s[-7]     0.970
12 s[-8]     0.943
13 s[-9]     0.921
14 s[-10]    0.797
15 s[-11]    0.723</code></pre>
</div>
</div>
</section>
<section id="residuals-and-ljung-box-test" class="level2">
<h2 class="anchored" data-anchor-id="residuals-and-ljung-box-test">Residuals and Ljung-Box test</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>ETS_fit <span class="sc">|&gt;</span> <span class="fu">select</span>(Damped_MAdM) <span class="sc">|&gt;</span> <span class="fu">gg_tsresiduals</span>(<span class="at">lag=</span><span class="dv">48</span>) <span class="sc">+</span> </span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Holt (M,N,M) Residual Plots"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project-1-Retail-Forecasting_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(ETS_fit) <span class="sc">|&gt;</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(.model <span class="sc">==</span> <span class="st">"Holt_MNM"</span>) <span class="sc">|&gt;</span></span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">features</span>(.innov, ljung_box, <span class="at">lag =</span> <span class="dv">24</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .model   lb_stat lb_pvalue
  &lt;chr&gt;      &lt;dbl&gt;     &lt;dbl&gt;
1 Holt_MNM    157.         0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>AR_fit <span class="sc">|&gt;</span> <span class="fu">select</span>(a4) <span class="sc">|&gt;</span> <span class="fu">gg_tsresiduals</span>(<span class="at">lag=</span><span class="dv">48</span>) <span class="sc">+</span> </span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"ARIMA(6,0,0)(2,1,0)[12] Residual Plots"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project-1-Retail-Forecasting_files/figure-html/unnamed-chunk-21-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(AR_fit) <span class="sc">|&gt;</span> <span class="fu">filter</span>(.model<span class="sc">==</span><span class="st">'a4'</span>) <span class="sc">|&gt;</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">features</span>(.innov, ljung_box, <span class="at">lag =</span> <span class="dv">24</span>, <span class="at">dof =</span> <span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .model lb_stat lb_pvalue
  &lt;chr&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 a4        22.7     0.122</code></pre>
</div>
</div>
<p>The innovation residuals for the ETS model look like they have a mean of 0. The residual plot shows a normal distribution. The ACF plot has patterns and has quite a few significant lags. This suggests that the residuals are auto-correlated. To further investigate if the residuals are white noise, the Ljung-Box test was used. The test produces a statistically significant p-value of 0, indicating significant auto-correlation.</p>
<p>For the ARIMA residuals, the innovation residual plot seems to have a mean of 0. The residual plot shows a normal distribution. The ACF plot also has patterns, and a few significant lags, meaning there is auto-correlation in the residuals.The the Ljung-Box test produces a p-value of 0.122, therefore the hypothesis that the residuals are not white noise is rejected.</p>
<p>Therefore the ARIMA(1,0,1)(0,1,1)[12] model is likely to produce the best forecast as it provided the lowest forecast error while maintaining well-behaved residuals. The ETS model fails to capture important temporal dependencies in the data and is therefore less likely to produce an accurate result.</p>
</section>
</section>
<section id="forecasting-using-full-data-set" class="level1">
<h1>Forecasting Using Full Data Set</h1>
<section id="fitting-on-the-models-on-the-full-data-set" class="level2">
<h2 class="anchored" data-anchor-id="fitting-on-the-models-on-the-full-data-set">Fitting on the models on the full data set</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>AR_best <span class="ot">&lt;-</span> retail_ts <span class="sc">|&gt;</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="fu">model</span>(<span class="fu">ARIMA</span>(<span class="fu">log</span>(Sales) <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> <span class="fu">pdq</span>(<span class="dv">6</span>,<span class="dv">0</span>,<span class="dv">0</span>) <span class="sc">+</span> <span class="fu">PDQ</span>(<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">0</span>)))</span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>ETS_best <span class="ot">&lt;-</span> retail_ts <span class="sc">|&gt;</span></span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(<span class="fu">ETS</span>(Sales <span class="sc">~</span> <span class="fu">error</span>(<span class="st">"M"</span>) <span class="sc">+</span> <span class="fu">trend</span>(<span class="st">"N"</span>) <span class="sc">+</span> <span class="fu">season</span>(<span class="st">"M"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="forecasting-2-years-ahead" class="level2">
<h2 class="anchored" data-anchor-id="forecasting-2-years-ahead">Forecasting 2 years ahead</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>ETS_fc <span class="ot">&lt;-</span> <span class="fu">forecast</span>(ETS_best, <span class="at">h=</span><span class="dv">24</span>)</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>ETS_fc <span class="sc">|&gt;</span></span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(retail_ts) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Turnover ($ Million)"</span>, <span class="at">title =</span> <span class="st">"ETS 24 Month Forecast of US Clothing Sales"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project-1-Retail-Forecasting_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>AR_fc <span class="ot">&lt;-</span> <span class="fu">forecast</span>(AR_best, <span class="at">h=</span><span class="dv">24</span>)</span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>AR_fc <span class="sc">|&gt;</span></span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(retail_ts) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Turnover ($ Million)"</span>, <span class="at">title =</span> <span class="st">"ARIMA 24 Month Forecast of US Clothing Sales"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project-1-Retail-Forecasting_files/figure-html/unnamed-chunk-23-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Both models produce forecasts that indicate predictable seasonal increases in retail demand during the holiday period, providing a useful basis for short-term planning. However, the widening prediction intervals indicate that uncertainty increases over time, which should be considered when using forecasts for planning decisions.</p>
</section>
</section>
<section id="benefits-and-limitations-of-the-models" class="level1">
<h1>Benefits and Limitations of the Models</h1>
<section id="comparing-arima-and-ets-for-this-dataset" class="level2">
<h2 class="anchored" data-anchor-id="comparing-arima-and-ets-for-this-dataset">Comparing ARIMA and ETS for this dataset</h2>
<p>An advantage of ETS is that it can handles trends and seasonality directly. On the other hand, ARIMA assumes linear relationships and stationarity, meaning that for this dataset, the ARIMA models required differencing.</p>
<p>An advantage of ARIMA models are that they capture lagged effects, whereas ETS models do not. Capturing lagged effects is important when modelling retail turnover. For example, an economic shock that cause low sales in one month may cause sales to still be low in the next month.</p>
</section>
<section id="comparing-arima-and-ets-to-other-models-for-the-dataset" class="level2">
<h2 class="anchored" data-anchor-id="comparing-arima-and-ets-to-other-models-for-the-dataset">Comparing ARIMA and ETS to other models for the dataset</h2>
<p>ARIMA and ETS predict purely on temporal patterns - trends and seasonality. There may be other relationships in the data ARIMA and ETS are not capturing.</p>
<p>Unlike ARIMA and ETS, dynamic modelling allows for a change in parameters and can also adapt/switch behaviour. Therefore, dynamic modelling is better at capturing structural shocks such as COVID-19.</p>
</section>
</section>
<section id="final-model-selection" class="level1">
<h1>Final Model Selection</h1>
<p>Based on AICc, out-of-sample forecast accuracy, and residual diagnostics, the ARIMA(1,0,1)(0,1,1)[12] model was selected as the final model.</p>
<p>This model achieved the lowest forecast error while maintaining residuals that resemble white noise, indicating that it adequately captures the underlying time-series structure.</p>
<p>This is likely because ARIMA explicitly models autocorrelation through autoregressive and moving average terms, allowing it to capture how shocks propagate over time. In contrast, ETS relies on smoothing components and does not fully account for serial dependence, which is reflected in the significant residual autocorrelation observed in the Ljung–Box test. Therefore, the ARIMA model appears to have capture the COVID shock more effectively than the ETS model.</p>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>This analysis developed and evaluated time-series forecasting models for monthly US clothing retail sales. Exploratory analysis revealed strong seasonal patterns and an upward trend, motivating the use of logarithmic transformation and seasonal differencing.</p>
<p>Among the models considered, ARIMA specifications provided the best overall performance. Residual diagnostics indicated that these models more effectively captured the underlying time-series structure compared to ETS, which exhibited significant remaining autocorrelation.</p>
<p>From a business perspective, the forecasts demonstrate consistent seasonal peaks in retail demand during late-year holiday periods. These insights can support operational decisions such as inventory planning, workforce allocation, and promotional scheduling.</p>
<p>Overall, the results highlight the importance of combining statistical modelling with domain understanding to produce forecasts that are both accurate and actionable.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>